FROM mcr.microsoft.com/dotnet/aspnet:10.0
USER root
RUN apt-get update && apt-get install -y --no-install-recommends curl libssl3 && rm -rf /var/lib/apt/lists/*
USER $APP_UID
WORKDIR /app
COPY publish-output/ .
ENTRYPOINT ["dotnet", "BreakfastProvider.Api.dll"]
