// ------------------------------------------------------------------------------
//  <auto-generated>
//      This code was generated by Reqnroll (https://reqnroll.net/).
//      Reqnroll Version:3.0.0.0
//      Reqnroll Generator Version:3.0.0.0
// 
//      Changes to this file may cause incorrect behavior and will be lost if
//      the code is regenerated.
//  </auto-generated>
// ------------------------------------------------------------------------------
#region Designer generated code
#pragma warning disable
using Reqnroll;
namespace BreakfastProvider.Tests.Component.ReqNRoll.Features.Muffins
{
    
    
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Reqnroll", "3.0.0.0")]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public partial class MuffinsCreationFeature : object, Xunit.IClassFixture<MuffinsCreationFeature.FixtureData>, Xunit.IAsyncLifetime
    {
        
        private global::Reqnroll.ITestRunner testRunner;
        
        private Xunit.ITestOutputHelper _testOutputHelper;
        
        private static string[] featureTags = ((string[])(null));
        
        private static global::Reqnroll.FeatureInfo featureInfo = new global::Reqnroll.FeatureInfo(new global::System.Globalization.CultureInfo("en-US"), "Features/Muffins", "Muffins Creation", "    /muffins - Creating apple cinnamon muffins with baking profiles and toppings", global::Reqnroll.ProgrammingLanguage.CSharp, featureTags, InitializeCucumberMessages());
        
#line 1 "MuffinsCreation.feature"
#line hidden
        
        public MuffinsCreationFeature(MuffinsCreationFeature.FixtureData fixtureData, Xunit.ITestOutputHelper testOutputHelper)
        {
            this._testOutputHelper = testOutputHelper;
        }
        
        public static async global::System.Threading.Tasks.Task FeatureSetupAsync()
        {
        }
        
        public static async global::System.Threading.Tasks.Task FeatureTearDownAsync()
        {
            await global::Reqnroll.TestRunnerManager.ReleaseFeatureAsync(featureInfo);
        }
        
        public async global::System.Threading.Tasks.Task TestInitializeAsync()
        {
            testRunner = global::Reqnroll.TestRunnerManager.GetTestRunnerForAssembly(featureHint: featureInfo);
            try
            {
                if (((testRunner.FeatureContext != null) 
                            && (testRunner.FeatureContext.FeatureInfo.Equals(featureInfo) == false)))
                {
                    await testRunner.OnFeatureEndAsync();
                }
            }
            finally
            {
                if (((testRunner.FeatureContext != null) 
                            && testRunner.FeatureContext.BeforeFeatureHookFailed))
                {
                    throw new global::Reqnroll.ReqnrollException("Scenario skipped because of previous before feature hook error");
                }
                if ((testRunner.FeatureContext == null))
                {
                    await testRunner.OnFeatureStartAsync(featureInfo);
                }
            }
        }
        
        public async global::System.Threading.Tasks.Task TestTearDownAsync()
        {
            if ((testRunner == null))
            {
                return;
            }
            try
            {
                await testRunner.OnScenarioEndAsync();
            }
            finally
            {
                global::Reqnroll.TestRunnerManager.ReleaseTestRunner(testRunner);
                testRunner = null;
            }
        }
        
        public void ScenarioInitialize(global::Reqnroll.ScenarioInfo scenarioInfo, global::Reqnroll.RuleInfo ruleInfo)
        {
            testRunner.OnScenarioInitialize(scenarioInfo, ruleInfo);
            testRunner.ScenarioContext.ScenarioContainer.RegisterInstanceAs<Xunit.ITestOutputHelper>(_testOutputHelper);
        }
        
        public async global::System.Threading.Tasks.Task ScenarioStartAsync()
        {
            await testRunner.OnScenarioStartAsync();
        }
        
        public async global::System.Threading.Tasks.Task ScenarioCleanupAsync()
        {
            await testRunner.CollectScenarioErrorsAsync();
        }
        
        private static global::Reqnroll.Formatters.RuntimeSupport.FeatureLevelCucumberMessages InitializeCucumberMessages()
        {
            return new global::Reqnroll.Formatters.RuntimeSupport.FeatureLevelCucumberMessages("Features/Muffins/MuffinsCreation.feature.ndjson", 12);
        }
        
        async System.Threading.Tasks.ValueTask Xunit.IAsyncLifetime.InitializeAsync()
        {
            try
            {
                await this.TestInitializeAsync();
            }
            catch (System.Exception e1)
            {
                try
                {
                    ((Xunit.IAsyncLifetime)(this)).DisposeAsync();
                }
                catch (System.Exception e2)
                {
                    throw new System.AggregateException("Test initialization failed", e1, e2);
                }
                throw;
            }
        }
        
        async System.Threading.Tasks.ValueTask System.IAsyncDisposable.DisposeAsync()
        {
            await this.TestTearDownAsync();
        }
        
        [global::Xunit.FactAttribute(DisplayName="A valid apple cinnamon muffin request should return a fresh batch")]
        [global::Xunit.TraitAttribute("FeatureTitle", "Muffins Creation")]
        [global::Xunit.TraitAttribute("Description", "A valid apple cinnamon muffin request should return a fresh batch")]
        [global::Xunit.TraitAttribute("Category", "happy-path")]
        public async global::System.Threading.Tasks.Task AValidAppleCinnamonMuffinRequestShouldReturnAFreshBatch()
        {
            string[] tagsOfScenario = new string[] {
                    "happy-path"};
            global::System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new global::System.Collections.Specialized.OrderedDictionary();
            string pickleIndex = "0";
            global::Reqnroll.ScenarioInfo scenarioInfo = new global::Reqnroll.ScenarioInfo("A valid apple cinnamon muffin request should return a fresh batch", null, tagsOfScenario, argumentsOfScenario, featureTags, pickleIndex);
            string[] tagsOfRule = ((string[])(null));
            global::Reqnroll.RuleInfo ruleInfo = null;
#line 5
    this.ScenarioInitialize(scenarioInfo, ruleInfo);
#line hidden
            if ((global::Reqnroll.TagHelper.ContainsIgnoreTag(scenarioInfo.CombinedTags) || global::Reqnroll.TagHelper.ContainsIgnoreTag(featureTags)))
            {
                await testRunner.SkipScenarioAsync();
            }
            else
            {
                await this.ScenarioStartAsync();
#line 6
        await testRunner.GivenAsync("a valid apple cinnamon muffin recipe with all ingredients", ((string)(null)), ((global::Reqnroll.Table)(null)), "Given ");
#line hidden
#line 7
        await testRunner.WhenAsync("the muffins are prepared", ((string)(null)), ((global::Reqnroll.Table)(null)), "When ");
#line hidden
#line 8
        await testRunner.ThenAsync("the muffin response should contain a valid batch with all ingredients", ((string)(null)), ((global::Reqnroll.Table)(null)), "Then ");
#line hidden
#line 9
        await testRunner.AndAsync("the cow service should have received a milk request for the muffins", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
            }
            await this.ScenarioCleanupAsync();
        }
        
        [global::Xunit.TheoryAttribute(DisplayName="Different muffin recipes should produce the expected batch")]
        [global::Xunit.TraitAttribute("FeatureTitle", "Muffins Creation")]
        [global::Xunit.TraitAttribute("Description", "Different muffin recipes should produce the expected batch")]
        [global::Xunit.InlineDataAttribute("Classic", "Plain Flour", "Granny Smith", "Ceylon", "180", "25", "Standard", "Streusel", "Light", "Icing Glaze", "Drizzle", "5", "2", "1", new string[0])]
        [global::Xunit.InlineDataAttribute("Rustic Wholesome", "Whole Wheat", "Honeycrisp", "Cassia", "175", "30", "Cast Iron", "Brown Sugar Crumb", "Heavy", "Maple Drizzle", "Light", "5", "2", "2", new string[0])]
        [global::Xunit.InlineDataAttribute("Spiced Deluxe", "Almond", "Pink Lady", "Saigon", "190", "20", "Silicone", "Cinnamon Sugar", "Heavy", "Cream Cheese Swirl", "Thick", "5", "2", "3", new string[0])]
        public async global::System.Threading.Tasks.Task DifferentMuffinRecipesShouldProduceTheExpectedBatch(string recipeName, string flour, string appleVariety, string cinnamonType, string temperature, string duration, string panType, string topping1, string amount1, string topping2, string amount2, string expectedIngredientCount, string expectedToppingCount, string @__pickleIndex, string[] exampleTags)
        {
            string[] tagsOfScenario = exampleTags;
            global::System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new global::System.Collections.Specialized.OrderedDictionary();
            argumentsOfScenario.Add("RecipeName", recipeName);
            argumentsOfScenario.Add("Flour", flour);
            argumentsOfScenario.Add("AppleVariety", appleVariety);
            argumentsOfScenario.Add("CinnamonType", cinnamonType);
            argumentsOfScenario.Add("Temperature", temperature);
            argumentsOfScenario.Add("Duration", duration);
            argumentsOfScenario.Add("PanType", panType);
            argumentsOfScenario.Add("Topping1", topping1);
            argumentsOfScenario.Add("Amount1", amount1);
            argumentsOfScenario.Add("Topping2", topping2);
            argumentsOfScenario.Add("Amount2", amount2);
            argumentsOfScenario.Add("ExpectedIngredientCount", expectedIngredientCount);
            argumentsOfScenario.Add("ExpectedToppingCount", expectedToppingCount);
            string pickleIndex = @__pickleIndex;
            global::Reqnroll.ScenarioInfo scenarioInfo = new global::Reqnroll.ScenarioInfo("Different muffin recipes should produce the expected batch", null, tagsOfScenario, argumentsOfScenario, featureTags, pickleIndex);
            string[] tagsOfRule = ((string[])(null));
            global::Reqnroll.RuleInfo ruleInfo = null;
#line 11
    this.ScenarioInitialize(scenarioInfo, ruleInfo);
#line hidden
            if ((global::Reqnroll.TagHelper.ContainsIgnoreTag(scenarioInfo.CombinedTags) || global::Reqnroll.TagHelper.ContainsIgnoreTag(featureTags)))
            {
                await testRunner.SkipScenarioAsync();
            }
            else
            {
                await this.ScenarioStartAsync();
                global::Reqnroll.Table table1 = new global::Reqnroll.Table(new string[] {
                            "Flour",
                            "Apples",
                            "Cinnamon"});
                table1.AddRow(new string[] {
                            string.Format("{0}", flour),
                            string.Format("{0}", appleVariety),
                            string.Format("{0}", cinnamonType)});
#line 12
        await testRunner.GivenAsync(string.Format("a muffin recipe \"{0}\" with the following ingredients:", recipeName), ((string)(null)), table1, "Given ");
#line hidden
#line 15
        await testRunner.AndAsync(string.Format("with baking at {0} degrees for {1} minutes in a \"{2}\" pan", temperature, duration, panType), ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
                global::Reqnroll.Table table2 = new global::Reqnroll.Table(new string[] {
                            "Name",
                            "Amount"});
                table2.AddRow(new string[] {
                            string.Format("{0}", topping1),
                            string.Format("{0}", amount1)});
                table2.AddRow(new string[] {
                            string.Format("{0}", topping2),
                            string.Format("{0}", amount2)});
#line 16
        await testRunner.AndAsync("the following muffin toppings:", ((string)(null)), table2, "And ");
#line hidden
#line 20
        await testRunner.WhenAsync("the muffins are prepared", ((string)(null)), ((global::Reqnroll.Table)(null)), "When ");
#line hidden
#line 21
        await testRunner.ThenAsync(string.Format("the muffin batch should have {0} ingredients", expectedIngredientCount), ((string)(null)), ((global::Reqnroll.Table)(null)), "Then ");
#line hidden
#line 22
        await testRunner.AndAsync(string.Format("the muffin response should include {0} toppings", expectedToppingCount), ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
            }
            await this.ScenarioCleanupAsync();
        }
        
        [global::Xunit.TheoryAttribute(DisplayName="Muffins endpoint called with an invalid field should return a bad request respons" +
            "e")]
        [global::Xunit.TraitAttribute("FeatureTitle", "Muffins Creation")]
        [global::Xunit.TraitAttribute("Description", "Muffins endpoint called with an invalid field should return a bad request respons" +
            "e")]
        [global::Xunit.InlineDataAttribute("Flour", "", "Flour is required", "\'Flour\' is required.", "Bad Request", "4", new string[0])]
        [global::Xunit.InlineDataAttribute("Apples", "", "Apples is required", "\'Apples\' is required.", "Bad Request", "5", new string[0])]
        [global::Xunit.InlineDataAttribute("Cinnamon", "", "Cinnamon is required", "\'Cinnamon\' is required.", "Bad Request", "6", new string[0])]
        [global::Xunit.InlineDataAttribute("Milk", "", "Milk is required", "\'Milk\' is required.", "Bad Request", "7", new string[0])]
        [global::Xunit.InlineDataAttribute("Eggs", "", "Eggs is required", "\'Eggs\' is required.", "Bad Request", "8", new string[0])]
        [global::Xunit.InlineDataAttribute("Cinnamon", "<script>alert(\'xss\')</script>", "XSS in cinnamon", "Cinnamon contains potentially dangerous content.", "Bad Request", "9", new string[0])]
        public async global::System.Threading.Tasks.Task MuffinsEndpointCalledWithAnInvalidFieldShouldReturnABadRequestResponse(string field, string value, string reason, string errorMessage, string responseStatus, string @__pickleIndex, string[] exampleTags)
        {
            string[] tagsOfScenario = exampleTags;
            global::System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new global::System.Collections.Specialized.OrderedDictionary();
            argumentsOfScenario.Add("Field", field);
            argumentsOfScenario.Add("Value", value);
            argumentsOfScenario.Add("Reason", reason);
            argumentsOfScenario.Add("Error Message", errorMessage);
            argumentsOfScenario.Add("Response Status", responseStatus);
            string pickleIndex = @__pickleIndex;
            global::Reqnroll.ScenarioInfo scenarioInfo = new global::Reqnroll.ScenarioInfo("Muffins endpoint called with an invalid field should return a bad request respons" +
                    "e", null, tagsOfScenario, argumentsOfScenario, featureTags, pickleIndex);
            string[] tagsOfRule = ((string[])(null));
            global::Reqnroll.RuleInfo ruleInfo = null;
#line 30
    this.ScenarioInitialize(scenarioInfo, ruleInfo);
#line hidden
            if ((global::Reqnroll.TagHelper.ContainsIgnoreTag(scenarioInfo.CombinedTags) || global::Reqnroll.TagHelper.ContainsIgnoreTag(featureTags)))
            {
                await testRunner.SkipScenarioAsync();
            }
            else
            {
                await this.ScenarioStartAsync();
#line 31
        await testRunner.GivenAsync(string.Format("a valid muffin request with \"{0}\" set to \"{1}\"", field, value), ((string)(null)), ((global::Reqnroll.Table)(null)), "Given ");
#line hidden
#line 32
        await testRunner.WhenAsync("the invalid muffin request is submitted", ((string)(null)), ((global::Reqnroll.Table)(null)), "When ");
#line hidden
#line 33
        await testRunner.ThenAsync(string.Format("the muffin response should contain error \"{0}\" with status \"{1}\"", errorMessage, responseStatus), ((string)(null)), ((global::Reqnroll.Table)(null)), "Then ");
#line hidden
            }
            await this.ScenarioCleanupAsync();
        }
        
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Reqnroll", "3.0.0.0")]
        [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
        public class FixtureData : object, Xunit.IAsyncLifetime
        {
            
            async System.Threading.Tasks.ValueTask Xunit.IAsyncLifetime.InitializeAsync()
            {
                await MuffinsCreationFeature.FeatureSetupAsync();
            }
            
            async System.Threading.Tasks.ValueTask System.IAsyncDisposable.DisposeAsync()
            {
                await MuffinsCreationFeature.FeatureTearDownAsync();
            }
        }
    }
}
#pragma warning restore
#endregion
