name: Get version

inputs:
  version-prefix: { type: string, required: false, default: "1.0" }

outputs:
  version:
    value: ${{ steps.get-version.outputs.version }}

  branch:
    value: ${{ steps.get-version.outputs.branch }}

runs:
  using: composite
  steps:
    - name: Get version
      id: get-version
      shell: bash
      run: |
        version='${{ inputs.version-prefix }}.${{ github.run_number }}'

        pr_number=${{ github.event.pull_request.number || 0 }}

        if [ '${{ github.ref }}' != 'refs/heads/main' ]; then
          if [ "$pr_number" -ne 0 ]; then
            version="${version}-pr-${pr_number}"
          else
            short_sha=$(echo "${{ github.sha }}" | cut -c1-7)
            version="${version}-dev-${short_sha}"
          fi
        fi
        echo "Setting version: $version   // github.ref: ${{ github.ref }}"
        echo "version=$version" >> $GITHUB_OUTPUT
        echo "branch=${GITHUB_HEAD_REF:-${GITHUB_REF#refs/heads/}}" >> $GITHUB_OUTPUT
