global using AwesomeAssertions;
global using Kronikol.Tracking;
global using Kronikol.xUnit3;
global using CurrentTestInfo = Kronikol.BDDfy.xUnit3.CurrentTestInfo;
global using Xunit;
global using BreakfastProvider.Tests.Component.BDDfy.Infrastructure;
global using BreakfastProvider.Tests.Component.Shared.Infrastructure.Configuration;
global using Settings = BreakfastProvider.Tests.Component.Shared.Infrastructure.Configuration.ComponentTestSettings;
global using BreakfastProvider.Tests.Component.Shared.Infrastructure.DependencyInjection;
global using BreakfastProvider.Tests.Component.Shared.Infrastructure.Hosting;
global using static BreakfastProvider.Tests.Component.Shared.Constants.IgnoreReasons;
