# kafka-dev-with-docker/part-09/client.properties
security.protocol=SASL_SSL
sasl.mechanism=PLAIN
sasl.jaas.config=org.apache.kafka.common.security.plain.PlainLoginModule required \
    username="kafka-user" \
    password="kafka-user-secret";
ssl.truststore.location=/opt/bitnami/kafka/config/certs/kafka.truststore.jks
ssl.truststore.password=certificatePassword123
ssl.keystore.location=/opt/bitnami/kafka/config/certs/kafka.keystore.jks
ssl.keystore.password=certificatePassword123
ssl.key.password=certificatePassword123
ssl.endpoint.identification.algorithm=